name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      -
        name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" >> .npmrc
          echo "@gordonfn:registry=https://npm.pkg.github.com" >> .npmrc
          echo ".npmrc" >> .gitignore
      -
        name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      -
        name: Install dependencies
        run: |
          npm install
          npm update @gordonfn/normalize
          npm audit fix
      -
        name: Build and test allowed values
        run: |
          npm run download
          npm run test
          echo "change=$(git status --porcelain)" >> $GITHUB_ENV
      -
        if: env.change
        name: Version bump
        run: |
          echo "tag=$(npm version patch)" >> $GITHUB_ENV
      - if: env.change
        name: Commit Changes
        run: |
          git add -A
          git commit -a -m 'ci: update schema dep'
          git tag ${{ env.tag }}
          git status
          git push "https://${GITHUB_ACTOR}:${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF#refs/*/} --follow-tags --force --tags
      -
        if: env.change
        name: Publish
        run: |
          npm publish
      -
        if: env.change
        name: Trigger @gordonfn/normalize rebuild
        run: |
          curl -X POST https://api.github.com/repos/gordonfn/normalize/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ github.token }} \
          --data '{"event_type": "guidelines", "client_payload": {}'